# üìå Avalia√ß√£o Sum√°ria

OBS: Suba o arquivo que deseja analisar, como aquele do nosso exemplo

[Clique para acessar os dados](https://docs.google.com/spreadsheets/d/1YQhDNSt1sOrzq6AKxyYG6wzRAvM-M7l7jJRIHunNB88/copy?gid=1190375422#gid=1190375422)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_receitas = pd.read_csv("/content/C√≥pia de Dados - TCC - Planilhas - Receitas.csv")

## 1Ô∏è‚É£ Verificando as Dimens√µes do DataFrame

üîπ O que faz?
* Retorna o n√∫mero de linhas e colunas do DataFrame.
* Ajuda a verificar se os dados foram carregados corretamente.
* √ötil para: Ter uma vis√£o r√°pida do tamanho do dataset.

In [3]:
df_receitas.shape

(1242, 15)

Curiosidade: Atributos s√£o propriedades est√°ticas de um objeto, n√£o precisam de par√™ntese, como m√©todos

## 2Ô∏è‚É£ Identificando os Tipos de Dados das Colunas

üîπ O que faz?
* Mostra informa√ß√µes gerais sobre o DataFrame.
* Inclui: O tipo de cada coluna, Quantidade de valores n√£o nulos (dados preenchidos), Total de colunas e registros
* √ötil para Identificar colunas num√©ricas e categ√≥ricas
* √ötil para Verificar se os tipos de dados est√£o corretos.

In [4]:
df_receitas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1242 entries, 0 to 1241
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Data Lan√ßamento             1242 non-null   object
 1   Id Atendimento              1242 non-null   int64
 2   Receita C√≥digo              1242 non-null   int64
 3   Quantidade Vendida          1242 non-null   int64
 4   Valor de venda              1242 non-null   object
 5   Cliente ID                  1242 non-null   object
 6   Cliente Sexo                1050 non-null   object
 7   Cliente Nome                1242 non-null   object
 8   Cliente Data Nascimento     1139 non-null   object
 9   Cliente Origem              673 non-null    object
 10  Cliente Cidade              1095 non-null   object
 11  Profissional Nome           1242 non-null   object
 12  Profissional Especialidade  1242 non-null   object
 13  Data de Pagamento           1242 non-null   object
 14  Forma Pagamento             1242 non-null   object
dtypes: int64(3), object(12)
memory usage: 145.7+ KB

üîπ √â poss√≠vel ver quantas linhas nulas perguntando "Ei, quantos nulos?" ‚õî

In [5]:
df_receitas.isna()

,Data Lan√ßamento,Id Atendimento,Receita C√≥digo,Quantidade Vendida,Valor de venda,Cliente ID,Cliente Sexo,Cliente Nome,Cliente Data Nascimento,Cliente Origem,Cliente Cidade,Profissional Nome,Profissional Especialidade,Data de Pagamento,Forma Pagamento
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1237,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1238,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1239,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1240,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1241,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

üîπ A pergunta retorna False ( = 0) e True ( = 1). Ora, e se somarmos? A soma nos dar√° o total de nulos

In [6]:
df_receitas.isna().sum()

Data Lan√ßamento                 0
Id Atendimento                  0
Receita C√≥digo                  0
Quantidade Vendida              0
Valor de venda                  0
Cliente ID                      0
Cliente Sexo                  192
Cliente Nome                    0
Cliente Data Nascimento       103
Cliente Origem                569
Cliente Cidade                147
Profissional Nome               0
Profissional Especialidade      0
Data de Pagamento               0
Forma Pagamento                 0
dtype: int64

üîπ Se quiser saber apenas dos tipos

In [7]:
df_receitas.dtypes

Data Lan√ßamento               object
Id Atendimento                 int64
Receita C√≥digo                 int64
Quantidade Vendida             int64
Valor de venda                object
Cliente ID                    object
Cliente Sexo                  object
Cliente Nome                  object
Cliente Data Nascimento       object
Cliente Origem                object
Cliente Cidade                object
Profissional Nome             object
Profissional Especialidade    object
Data de Pagamento             object
Forma Pagamento               object
dtype: object

Algum dado tem tipo errado? üòÆ

## 3Ô∏è‚É£  Obtendo Estat√≠sticas Descritivas das Colunas Num√©ricas

In [8]:
df_receitas.describe()

       Id Atendimento  Receita C√≥digo  Quantidade Vendida
count    1.242000e+03    1.242000e+03         1242.000000
mean     4.516836e+13    8.819154e+08            1.058776
std      2.445861e+11    6.105148e+06            0.334324
min      4.448788e+13    8.799386e+08            1.000000
25%      4.499588e+13    8.799411e+08            1.000000
50%      4.526888e+13    8.799491e+08            1.000000
75%      4.536990e+13    8.817329e+08            1.000000
max      4.544393e+13    9.397083e+08            6.000000

üîπ O que faz?
* Exibe estat√≠sticas resumidas para todas as colunas num√©ricas.
* Inclui m√©tricas como m√©dia, desvio padr√£o, m√≠nimo, m√°ximo e quartis.

In [9]:
#Use um par√¢metro que filtra colunas num√©ricas, para ter estat√≠sticas aplic√°veis a dados num√©ricos

df_receitas.describe(include=[float, int])

       Id Atendimento  Receita C√≥digo  Quantidade Vendida
count    1.242000e+03    1.242000e+03         1242.000000
mean     4.516836e+13    8.819154e+08            1.058776
std      2.445861e+11    6.105148e+06            0.334324
min      4.448788e+13    8.799386e+08            1.000000
25%      4.499588e+13    8.799411e+08            1.000000
50%      4.526888e+13    8.799491e+08            1.000000
75%      4.536990e+13    8.817329e+08            1.000000
max      4.544393e+13    9.397083e+08            6.000000

Aqui reparamos que os identificadores deveriam ter sido entendidos como string (Sempre como string, lembre-se do zero √† esquerda), mudan√ßa que vamos aplicar posteriormente.

## 4Ô∏è‚É£  Obtendo Estat√≠sticas Descritivas das Colunas Categ√≥ricas

Tamb√©m √© interessante verificarmos **quais os valores existentes na coluna**. Para isso, podemos usar a fun√ß√£o  <font color = "orange">**`.unique()`</font>**:

In [10]:
df_receitas

,Data Lan√ßamento,Id Atendimento,Receita C√≥digo,Quantidade Vendida,Valor de venda,Cliente ID,Cliente Sexo,Cliente Nome,Cliente Data Nascimento,Cliente Origem,Cliente Cidade,Profissional Nome,Profissional Especialidade,Data de Pagamento,Forma Pagamento
0,18/10/2021,44487881736038,879941033,1,"R$ 5.989,00",e\aez\eae,F,Eneida Dos Reis,1975-01-01,Indica√ß√£o,BH,M√°rio Monteiro Campos,Cirurgia Pl√°stica,2021-10-21,TED/DOC
1,18/10/2021,44487881736038,879941033,1,"R$ 5.989,00",881736038aeeaeeaaeea,F,Eneida Dos Reis,1975-01-01,Indica√ß√£o,BH,M√°rio Monteiro Campos,Cirurgia Pl√°stica,2021-10-21,TED/DOC
2,18/10/2021,44487881736038,879941033,1,"R$ 5.989,00",881736038aeeae,F,Eneida Dos Reis,1975-01-01,Indica√ß√£o,BH,M√°rio Monteiro Campos,Cirurgia Pl√°stica,2021-10-21,TED/DOC
3,18/10/2021,44487881736038,879941033,1,"R$ 5.989,00",881736038,F,Eneida Dos Reis,1975-01-01,Indica√ß√£o,BH,M√°rio Monteiro Campos,Cirurgia Pl√°stica,2021-10-21,TED/DOC
4,08/11/2021,44508881735973,879941073,1,"R$ 10.535,00",881735973,F,Cl√°udia Alves Rodrigues Moura,1972-06-22,Indica√ß√£o,BH,Talia Estev√£o de Oliveira,Cirurgia Pl√°stica,2021-11-08,Pix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1237,28/05/2024,45440933201102,881732900,1,"R$ 300,00",933201102,Feminino,Rafaela Lima Gon√ßalves,NaN,Indica√ß√£o,Belo Horizonte,Mateus Henrique Lopes Ribeiro,Cirurgia Pl√°stica,2024-06-10,Pix
1238,29/05/2024,45441920676452,881732900,1,"R$ 250,00",920676452,Feminino,Tatiane Gon√ßalves Martins,1994-11-11,Rede Social,Jo√£o Monlevade,M√°rio Tiago Rezende Pires,Cirurgia Pl√°stica,2024-06-05,Pix
1239,29/05/2024,45441923179337,879938579,1,"R$ 1.500,00",923179337,Feminino,Vanessa Lima Martins,1977-12-27,Rede Social,Jo√£o Monlevade,Talia Estev√£o de Oliveira,Cirurgia Pl√°stica,2024-06-28,Cart√£o de cr√©dito √† vista
1240,31/05/2024,45443933211803,881732900,1,"R$ 250,00",933211803,Feminino,Rafaela Martins Oliveira,1998-01-26,NaN,Belo Horizonte,M√°rio Tiago Rezende Pires,Cirurgia Pl√°stica,2024-06-12,Pix
1241,31/05/2024,45443913709155,881732900,1,"R$ 250,00",913709155,Feminino,Vanessa Lima Ferreira,1995-08-01,NaN,Lagoa Santa,M√°rio Tiago Rezende Pires,Cirurgia Pl√°stica,2024-06-12,Pix

In [11]:
df_receitas['Cliente Sexo'].unique()

array(['F', 'M', nan, 'Feminino', 'Masculino'], dtype=object)

üîπ O que faz?
* Exibe estat√≠sticas resumidas para todas as colunas categ√≥ricas
* top ‚Üí O valor mais frequente na coluna.
* freq ‚Üí Quantidade de vezes que o valor mais frequente aparece.

In [12]:
# Use um par√¢metro que filtra colunas categ√≥ricas, para ter estat√≠sticas aplic√°veis a dados categ√≥ricos (fict√≠cios)

df_receitas.describe(include=[object])

,Data Lan√ßamento,Valor de venda,Cliente ID,Cliente Sexo,Cliente Nome,Cliente Data Nascimento,Cliente Origem,Cliente Cidade,Profissional Nome,Profissional Especialidade,Data de Pagamento,Forma Pagamento
count,1242,1242,1242,1050,1242,1139,673,1095,1242,1242,1242,1242
unique,366,200,682,4,679,596,4,9,16,8,499,6
top,29/02/2024,"R$ 300,00",881735998,F,Denise Marques Casa Nova,1982-08-04,Indica√ß√£o,BH,J√∫lia Duarte Barbosa,Cirurgia Pl√°stica,2024-04-07,Pix
freq,49,193,27,536,27,27,454,611,266,624,17,878

In [13]:
# Usando o m√©todo .value_counts() em uma coluna espec√≠fica √© poss√≠vel verificar sua distribui√ß√£o de valores

df_receitas["Cliente Origem"].value_counts()

Cliente Origem
Indica√ß√£o      454
Rede Social    102
Conv√™nio        96
Google          21
Name: count, dtype: int64

In [14]:
# Caso queira contar n√∫meros de nulos, adicione como par√¢metro do value_counts()

df_receitas["Cliente Origem"].value_counts(dropna=False)

Cliente Origem
NaN            569
Indica√ß√£o      454
Rede Social    102
Conv√™nio        96
Google          21
Name: count, dtype: int64

In [15]:
# Caso queira na verdade o percentual, adicione como par√¢metro de value_counts()

df_receitas["Cliente Origem"].value_counts(dropna=False, normalize=True)

Cliente Origem
NaN            0.458132
Indica√ß√£o      0.365539
Rede Social    0.082126
Conv√™nio       0.077295
Google         0.016908
Name: proportion, dtype: float64

In [16]:
# Se quer multiplicar por 100, basta multiplicar por 100

df_receitas["Cliente Origem"].value_counts(dropna=False, normalize=True) * 100

Cliente Origem
NaN            45.813205
Indica√ß√£o      36.553945
Rede Social     8.212560
Conv√™nio        7.729469
Google          1.690821
Name: proportion, dtype: float64